# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Keks",
  "email": "keks222@example.com",
  "password": "123456",
  "userRole": "basic"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks222@example.com",
  "password": "123456"
}

###
